name: Reusable Cert Renew

on:
  workflow_dispatch:
    inputs:
      domain:
        required: true
        type: string
      ssh_key:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  renew_certificate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          sudo apt install python3-git

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ inputs.ssh_key }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 2222 ${{ inputs.domain }} >> ~/.ssh/known_hosts
          sudo apt-get install sshpass

      - name: Make script executable
        run: chmod +x ./renewal.py

      - name: Run the renewal script
        env:
          CF_Token: ${{ secrets.CF_Token }}
          domain: ${{ inputs.domain }}
          path: ${{ inputs.path }}
        run: python ./test.py
