name: all clients cert renew

on:
  schedule:
    # Runs every Friday at 00:00
    - cron: '0 0 * * FRI'
  workflow_dispatch:

jobs:
  renew_certificate:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      -  name: checkout repository
         uses: actions/checkout@v3
         
      -  name: install yq to read clients 
         run: |
              sudo wget https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64 -O /usr/local/bin/yq
              sudo chmod +x /usr/local/bin/yq
              sudo apt install --only-upgrade gh         
      -  name: read clienst from yaml file using yq
         env: 
           CF_Token: ${{secrets.CF_Token}}
         run: |
              #clients=$(yq eval '.clients[]' ./cert_renew/clients.yaml)
              for client in $(yq '.clients[]' ./cert_renew/clients.yaml); do
                export domain=$(echo $client | yq eval '.domain' -)
                export path=$(echo $client | yq eval '.path' -)
                ssh_key=$(echo $client | yq eval '.ssh_key' -)
                mkdir -p ~/.ssh
                echo "${ssh_key}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -p 2222 154.180.31.255 >> ~/.ssh/known_hosts
                sudo apt-get install sshpass
                chmod -x ./test.py
                python ./test.py
              done

