name: all clients cert renew

on:
  schedule:
    # Runs every Friday at 00:00
    - cron: '0 0 * * FRI'
  workflow_dispatch:

jobs:
  renew_certificate:
    runs-on: ubuntu-latest
    steps:
      -  name: checkout repository
         uses: actions/checkout@v3
         
      -  name: install yq to read clients 
         run: |
              sudo wget https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64 -O /usr/local/bin/yq
              sudo chmod +x /usr/local/bin/yq
      
      - name: Verify yq installation
        run: yq --version
         
      -  name: read clienst from yaml file using yq
         run: |
              clients=$(yq eval '.clients[] ./cert_renew/clients.yaml')
              for client in clients : do
                $domain= $(echo $client | yq eval 'domain')
                $ssh_key= $(echo $client | yq eval 'ssh_key')
                $path= $(echo $client | yq eval 'path')
                uses: ./.github/actions/cert-renew/
                with:
                  domain= "$domain"
                  ssh_key= "$ssh_key"
                  path= "$path"
