name: cert renew

on:
  schedule:
    # Runs every Friday at 00:00
    - cron: '0 0 * * FRI'
  workflow_dispatch:
jobs:
  renewing_certifcate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: installing python
        uses: actions/setup-python@v4
      - name: install depandancies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          sudo apt install python3-git
     # - name: ssh install
      #  uses: tanmancan/action-setup-ssh-agent-key@1.0.0
       # with: 
        #    ssh-private-key: ${{ secrets.MY_LAB_KEY }}
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$MY_LAB_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H zeyad@154.180.31.255 >> ~/.ssh/known_hosts
      - name: SSH to Laptop and Run Command
        run: |
          ssh -i ~/.ssh/id_rsa zeyad@154.180.31.255
        env:
          SSH_PRIVATE_KEY: ${{ secrets.MY_LAB_KEY }}
      - name: Make script executable
        run: chmod +x ./renewal.py

      - name: running the script
        env:
          CF_Token: ${{secrets.CF_Token}}
          domain:  "office.3es-eg.uk"
        run: python ./renewal.py
        
