name: Weekly Workflow

on:
  schedule:
    # Runs every Friday at 00:00
    - cron: '0 0 * * FRI'
  workflow_dispatch:
jobs:
  refreshing_ttlock_token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # For Bash script example
    - name: Make script executable
      run: chmod +x ./refresh_token.sh

    - name: Run the Bash script
      run: ./refresh_token.sh
