name: Weekly Workflow

on:
  workflow_dispatch:
jobs:
  refreshing_ttlock_token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # For Bash script example
    - name: Make script executable
      run: chmod +x ./refresh_token.sh

    - name: Run Hossam Refresh Token
      env:
        client_id: ${{secrets.TTLOCK_HOSSAM_CLIENT_ID}}
        client_secret: ${{secrets.TTLOCK_HOSSAM_CLIENT_SECRET}}
        refresh_token: ${{secrets.TTLOCK_HOSSAM_REFRESH_TOKEN}}
      run: ./refresh_token.sh
      
    - name: Run Office Refresh Token
      env:
        client_id: ${{secrets.TTLOCK_OFFICE_CLIENT_ID}}
        client_secret: ${{secrets.TTLOCK_OFFICE_CLIENT_SECRET}}
        refresh_token: ${{secrets.TTLOCK_OFFICE_REFRESH_TOKEN}}
      run: ./refresh_token.sh
